name: Deploy MuleSoft app to Cloudhub (dev)

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run:  echo {{ secrets.ANYPOINT_CLIENT_ID }}

      
